name: Bot Promos Buscalibre

on:
  schedule:
    # 1. Revisión de las horas "en punto" (02:00, 10:00, 17:00 y 22:00 UTC)
    # Equivale a las 22:00 (10pm), 06:00 (6am), 13:00 (1pm) y 18:00 (6pm) de Chile
    - cron: '0 2,10,17,22 * * *'
    
    # 2. Revisión de la media hora (04:30 UTC)
    # Equivale a las 00:30 (12:30am) de Chile
    - cron: '30 4 * * *'
    
  workflow_dispatch: # Permite ejecutarlo manualmente cuando quieras

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v4

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Instalar dependencias
      run: npm install

    - name: Ejecutar Bot
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        MONGO_URI: ${{ secrets.MONGO_URI }}
      run: node index.js
