name: Bot Promos Buscalibre

on:
  schedule:
    # Se ejecuta a las 00:00, 13:00 y 18:00 UTC
    # (Equivale aproximadamente a las 20:00, 09:00 y 14:00 de Chile)
    - cron: '0 0,13,18 * * *'
  workflow_dispatch: # Permite ejecutarlo manualmente

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v4

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Instalar dependencias
      run: npm install

    # PASO NUEVO: Forzar la instalación del motor de Chrome
    - name: Instalar Chrome para Puppeteer
      run: npx puppeteer browsers install chrome

    - name: Ejecutar Bot
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        MONGO_URI: ${{ secrets.MONGO_URI }}
      run: node index.js
